<?php

namespace InventarioBundle\Repository;

/**
 * ProveedoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedoresRepository extends \Doctrine\ORM\EntityRepository
{
}
