<?php

namespace InventarioBundle\Repository;

/**
 * UserPerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPerfilRepository extends \Doctrine\ORM\EntityRepository
{
}
